[buildpack]
id = "genericlawcoder/heroku-buildpack-python-main"
name = "Heroku Buildpack Python Main"
version = "1.0.0"

[publish.Ignore]
files = [
  ".github/",
  "builds/",
  "spec/",
  ".gitignore",
  ".rubocop.yml",
  "Gemfile",
  "Gemfile.lock",
  "hatchet.json",
  "hatchet.lock",
  "Makefile",
]
