api = "0.2"

[buildpack]
id = "genericlawcoder/heroku-buildpack-python-main"
name = "Heroku Buildpack Python Main"
version = "2.1.1"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.focal"

[publish.Ignore]
files = [
  ".github/",
  "builds/",
  "spec/",
  ".gitignore",
  ".rubocop.yml",
  "Gemfile",
  "Gemfile.lock",
  "hatchet.json",
  "hatchet.lock",
  "Makefile",
]
